### ISSUE TITLE
prmon_plot.py by default requests packages which are not needed

### ISSUE THREAD

**Issue by qgl90** [HSF/prmon#244]
In LHCb, we inherith prmon and prmon_plot.py when loading a 'default environment' . Such default environment has not the seaborn style plotting, the code fails 

```bash
$|=>lb-conda default /cvmfs/lhcbdev.cern.ch/conda/envs/default/2024-07-10_13-01/linux-64/bin/prmon_plot.py --input prmon.log   --xvar wtime --yvar vmem,pss,rss,swap --yunit GBTraceback (most recent call last):
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/default/2024-07-10_13-01/linux-64/lib/python3.12/site-packages/matplotlib/style/core.py", line 137, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/default/2024-07-10_13-01/linux-64/lib/python3.12/site-packages/matplotlib/__init__.py", line 866, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/default/2024-07-10_13-01/linux-64/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/default/2024-07-10_13-01/linux-64/lib/python3.12/site-packages/matplotlib/__init__.py", line 843, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn-whitegrid'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/default/2024-07-10_13-01/linux-64/bin/prmon_plot.py", line 16, in <module>
    plt.style.use("seaborn-whitegrid")
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/default/2024-07-10_13-01/linux-64/lib/python3.12/site-packages/matplotlib/style/core.py", line 139, in use
    raise OSError(
OSError: 'seaborn-whitegrid' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
```

The suggestion is to not throw the error but rather allow the plotting to run regardless.

**Comment by amete** [comment]
Thanks for reporting @qgl90. It looks like `matplotlib` renamed some of the built-in `seaborn` styles (those that are outdated w.r.t what `seaborn` provides these days). #245 should address this issue.
