### ISSUE TITLE
Reading from smaps sometimes throws

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#39]
Testing some improvements in "extreme" conditions, I see that `prmon` is core dumping on occasion:

```sh
[root@577ee70de0aa tests]# ../prmon -- ./burner -p 100 -c 0.1 -t 10
Will run for 10s using 100 process(es) and 10 thread(s)
Children will run for 1s
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_filebuf::underflow error reading the file
Aborted (core dumped)
[root@577ee70de0aa tests]# gdb ../prmon core
[...]
Core was generated by `../prmon -- ./burner -p 100 -c 0.1 -t 10'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1d121b51f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.x86_64 libgcc-4.8.5-16.el7_4.2.x86_64 libstdc++-4.8.5-16.el7_4.2.x86_64
(gdb) bt
#0  0x00007f1d121b51f7 in raise () from /lib64/libc.so.6
#1  0x00007f1d121b68e8 in abort () from /lib64/libc.so.6
#2  0x00007f1d12abbac5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007f1d12ab9a36 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f1d12ab9a63 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007f1d12ab9c83 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007f1d12b0ee07 in std::__throw_ios_failure(char const*) () from /lib64/libstdc++.so.6
#7  0x00007f1d12b1125e in std::basic_filebuf<char, std::char_traits<char> >::underflow() () from /lib64/libstdc++.so.6
#8  0x00007f1d12ad9cdd in std::istream::sentry::sentry(std::istream&, bool) () from /lib64/libstdc++.so.6
#9  0x00007f1d12ad1487 in std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () from /lib64/libstdc++.so.6
#10 0x0000000000419bf6 in memmon::update_stats (this=0x7fff47f40b30, pids=...) at /mnt/code/prmon/package/src/memmon.cpp:33
#11 0x0000000000408c0b in MemoryMonitor (mpid=mpid@entry=11061, filename="prmon.txt", jsonSummary="prmon.json", interval=interval@entry=1, netdevs=std::vector of length 0, capacity 0)
    at /mnt/code/prmon/package/src/prmon.cpp:188
#12 0x0000000000406129 in main (argc=<optimized out>, argv=<optimized out>) at /mnt/code/prmon/package/src/prmon.cpp:358
```

(for reference, this is at 8ca4872aa0c1c1ac770cc52d65b2fb5ec70123e3).

This is in `memmon.cpp:33`, while the smaps buffer is being read. Although ifstreams do not usually throw (unless `std::ios::exceptions` is set), it seems that they will throw if the whole file disappears from `/proc`.

So we need to protect against these exceptions in the loop. Although they are being seen for the smaps buffer (which is the largest/slowest status file to parse), I suppose they could in principle happen anywhere, so probably best to catch in the main monitoring loop and skip an iteration if this occurs.

**Comment by graeme-a-stewart** [comment]
Fixed in #37.
